spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Forwarded
        - RemoveRequestHeader=X-Forwarded-For
        - AddRequestHeader=X-Forwarded-Host, ${request.headers.Host}
        - AddRequestHeader=X-Forwarded-Port, "80"
        - AddRequestHeader=X-Forwarded-Proto, "http"
      routes:
        - id: catalogue-service-route
          uri: lb://ministore-catalogue-service
          predicates:
            - Host=catalogue.api.mini.store.127.0.0.1.nip.io
          filters:
            - PreserveHostHeader
        - id: feedback-service-route
          uri: lb://ministore-feedback-service
          predicates:
            - Host=feedback.api.mini.store.127.0.0.1.nip.io
          filters:
            - PreserveHostHeader
        - id: manager-app-route
          uri: lb://ministore-manager-app
          predicates:
            - Host=manager.mini.store.127.0.0.1.nip.io
          filters:
            - PreserveHostHeader
        - id: customer-app-route
          uri: lb://ministore-customer-app
          predicates:
            - Host=customer.mini.store.127.0.0.1.nip.io
          filters:
            - PreserveHostHeader
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ministore-eureka-server-svc.ministore.svc.cluster.local:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://tempo-svc.ministore.svc.cluster.local:9411/api/v2/spans