eureka:
  client:
    service-url:
      defaultZone: http://ministore-eureka-server-svc.ministore.svc.cluster.local:8761/eureka/
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.mini.store.192.168.49.2.nip.io/realms/ministore
        registration:
          keycloak:
            client-id: eureka-server-k8s
            client-secret: eFGYjlkGgzAUAg1uqmdx16TSsTFc4AHB
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.mini.store.192.168.49.2.nip.io/realms/ministore