spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.mini.store.127.0.0.1.nip.io/realms/ministore
        registration:
          keycloak:
            client-id: customer-app-k8s
            client-secret: PAOdUpiSxZJXOfcV3GxBJewImmw0DJ5e
          metrics:
            client-id: customer-app-k8s
            client-secret: PAOdUpiSxZJXOfcV3GxBJewImmw0DJ5e
          discovery:
            client-id: customer-app-k8s
            client-secret: PAOdUpiSxZJXOfcV3GxBJewImmw0DJ5e
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ministore-eureka-server-svc.ministore.svc.cluster.local:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tempo-svc.ministore.svc.cluster.local:9411/api/v2/spans